name: ethereum_address
description: A dart library to generate, checksum, and validate Ethereum addresses
version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  convert: ^3.0.0
  pointycastle: ^3.0.0-nullsafety.2


dev_dependencies:
  pedantic: ^1.11.0